CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_KEYBOARD_NAME="Corne"
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_DISPLAY_TICK_PERIOD_MS=250
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_WIDGET_WPM_STATUS=n
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=n
CONFIG_ZMK_DONGLE_DISPLAY_MODIFIERS=n
CONFIG_ZMK_DONGLE_DISPLAY_LAYER=n
CONFIG_ZMK_DONGLE_DISPLAY_WPM=n
CONFIG_LV_Z_VDB_SIZE=32
